Repository Log-Road/dias, pull requests merged in 2024-08, with the labels that each got.

#47 fix: cd yml file fixed with env
  .github/workflows/cd.yml
  apps/admin-server/src/club/club.controller.interface.ts
  apps/admin-server/src/club/club.controller.ts
  apps/admin-server/src/club/club.module.ts
  apps/admin-server/src/club/test/club.controller.spec.ts
  apps/admin-server/src/club/test/club.service.spec.ts
  apps/admin-server/src/prisma/prisma.service.ts
Labels: fix

#48 feat: getArchive 개발
  apps/asset-server/src/prisma/prisma.service.ts
  apps/asset-server/src/prisma/schema.prisma
  apps/asset-server/src/road/dto/request/getArchive.request.dto.ts
  apps/asset-server/src/road/dto/response/getArchive/competition.dto.ts
  apps/asset-server/src/road/dto/response/getArchive/getArchive.response.dto.ts
  apps/asset-server/src/road/dto/response/getArchive/project.dto.ts
  apps/asset-server/src/road/road.controller.ts
  apps/asset-server/src/road/road.service.ts
  apps/asset-server/src/road/test/road.controller.spec.ts
  apps/asset-server/src/road/test/road.service.spec.ts
Labels: feat

#49 feat: getClub
  apps/admin-server/src/club/club.controller.ts
  apps/admin-server/src/club/club.service.ts
  apps/admin-server/src/guard/adminValidator/adminValidator.guard.ts
  apps/admin-server/src/prisma/prisma.service.ts
  apps/dias/src/auth/dto/response/signIn.dto.ts
  apps/dias/src/auth/strategies/jwt/jwt.strategy.service.ts
Labels: feat, fix

#50 feat: create competition func
  apps/asset-server/src/prisma/prisma.service.ts
  apps/asset-server/src/road/dto/request/competition.request.dto.ts
  apps/asset-server/src/road/dto/response/common/project.dto.ts
  apps/asset-server/src/road/dto/response/competition/competition.response.dto.ts
  apps/asset-server/src/road/dto/response/getArchive/getArchive.response.dto.ts
  apps/asset-server/src/road/road.controller.ts
  apps/asset-server/src/road/road.service.ts
  apps/asset-server/src/road/test/road.controller.spec.ts
  apps/asset-server/src/road/test/road.service.spec.ts
Labels: feat

#51 feat: patchClubStatus
  README.md
  apps/admin-server/src/club/club.controller.interface.ts
  apps/admin-server/src/club/club.controller.ts
  apps/admin-server/src/club/club.service.interface.ts
  apps/admin-server/src/club/club.service.ts
  apps/admin-server/src/club/dto/req/modifyClub.request.dto.ts
  apps/admin-server/src/prisma/prisma.service.ts
Labels: feat

#52 feat: deleteClub
  README.md
  apps/admin-server/src/club/club.controller.ts
  apps/admin-server/src/club/club.service.ts
  apps/admin-server/src/club/dto/req/deleteClub.request.dto.ts
  apps/admin-server/src/prisma/prisma.service.ts
Labels: feat

#53 feat: getProject
  apps/asset-server/src/prisma/prisma.service.ts
  apps/asset-server/src/road/dto/request/project.request.dto.ts
  apps/asset-server/src/road/dto/response/getProject.response.dto.ts
  apps/asset-server/src/road/road.controller.ts
  apps/asset-server/src/road/road.service.ts
  apps/asset-server/src/road/test/road.controller.spec.ts
  apps/asset-server/src/road/test/road.service.spec.ts
Labels: feat

#54 feat:: search project
  apps/asset-server/src/prisma/prisma.service.ts
  apps/asset-server/src/road/dto/request/search.request.dto.ts
  apps/asset-server/src/road/dto/response/search.response.dto.ts
  apps/asset-server/src/road/road.controller.ts
  apps/asset-server/src/road/road.service.ts
  apps/asset-server/src/road/test/road.controller.spec.ts
  apps/asset-server/src/road/test/road.service.spec.ts
Labels: feat

#58 test:guard
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  apps/admin-server/src/club/test/club.controller.spec.ts
  apps/admin-server/src/guard/adminValidator/adminValidator.guard.spec.ts
  apps/admin-server/src/guard/adminValidator/adminValidator.guard.ts
  apps/dias/src/prisma/schema.prisma
Labels: fix

#59 Feat/competition
  apps/admin-server/src/admin-server.module.ts
  apps/admin-server/src/club/club.controller.interface.ts
  apps/admin-server/src/club/club.controller.ts
  apps/admin-server/src/club/club.module.ts
  apps/admin-server/src/club/club.service.interface.ts
  apps/admin-server/src/club/club.service.ts
  apps/admin-server/src/club/dto/request/deleteClub.request.dto.ts
  apps/admin-server/src/club/dto/request/getClub.request.dto.ts
  apps/admin-server/src/club/dto/request/modifyClub.request.dto.ts
  apps/admin-server/src/club/dto/request/postClub.request.dto.ts
  apps/admin-server/src/club/dto/response/deleteClub.response.dto.ts
  apps/admin-server/src/club/dto/response/getClub.response.dto.ts
  apps/admin-server/src/club/dto/response/modifyClub.response.dto.ts
  apps/admin-server/src/club/dto/response/postClub.response.dto.ts
  apps/admin-server/src/club/test/club.controller.spec.ts
  apps/admin-server/src/club/test/club.service.spec.ts
  apps/admin-server/src/competition/competition.controller.interface.ts
  apps/admin-server/src/competition/competition.controller.ts
  apps/admin-server/src/competition/competition.module.ts
  apps/admin-server/src/competition/competition.service.interface.ts
  apps/admin-server/src/competition/competition.service.ts
  apps/admin-server/src/competition/dto/request/getNonVoterList.request.dto.ts
  apps/admin-server/src/competition/dto/request/patchCompetition.request.dto.ts
  apps/admin-server/src/competition/dto/request/postAwards.request.dto.ts
  apps/admin-server/src/competition/dto/request/postCompetition.request.dto.ts
  apps/admin-server/src/competition/dto/response/getCompetition.response.dto.ts
  apps/admin-server/src/competition/dto/response/getCompetitionList.response.dto.ts
  apps/admin-server/src/competition/dto/response/getNonVoterList.response.dto.ts
  apps/admin-server/src/competition/dto/response/getRecentCompetitions.response.dto.ts
  apps/admin-server/src/competition/dto/response/getVotingPrefecture.response.dto.ts
  apps/admin-server/src/competition/dto/response/patchCompetition.response.dto.ts
  apps/admin-server/src/competition/dto/response/postAwards.response.dto.ts
  apps/admin-server/src/competition/dto/response/postCompetition.response.dto.ts
  apps/admin-server/src/competition/test/competition.controller.spec.ts
  apps/admin-server/src/competition/test/competition.service.spec.ts
  apps/admin-server/src/guard/adminValidator/adminValidator.guard.ts
  apps/admin-server/src/main.ts
  apps/admin-server/src/prisma/prisma.service.ts
  apps/admin-server/src/prisma/schema.prisma
Labels: feat

#60 feat: postAwards 수상
  apps/admin-server/src/competition/competition.controller.interface.ts
  apps/admin-server/src/competition/competition.controller.ts
  apps/admin-server/src/competition/competition.service.interface.ts
  apps/admin-server/src/competition/competition.service.ts
  apps/admin-server/src/competition/test/competition.controller.spec.ts
  apps/admin-server/src/competition/test/competition.service.spec.ts
  apps/admin-server/src/prisma/prisma.service.ts
  apps/admin-server/src/prisma/schema.prisma
Labels: feat

#61 feat: getCompetition
  apps/admin-server/src/competition/competition.controller.interface.ts
  apps/admin-server/src/competition/competition.controller.ts
  apps/admin-server/src/competition/competition.service.interface.ts
  apps/admin-server/src/competition/competition.service.ts
  apps/admin-server/src/competition/dto/request/patchCompetition.request.dto.ts
  apps/admin-server/src/competition/dto/response/getCompetitionList.response.dto.ts
  apps/admin-server/src/competition/test/competition.controller.spec.ts
  apps/admin-server/src/competition/test/competition.service.spec.ts
  apps/admin-server/src/prisma/prisma.service.ts
  apps/admin-server/src/prisma/schema.prisma
Labels: feat

#64 feat: patchCompetition
  .github/workflows/cd.yml
  apps/admin-server/src/competition/competition.controller.ts
  apps/admin-server/src/competition/competition.service.ts
  apps/admin-server/src/competition/dto/request/patchCompetition.request.dto.ts
  apps/admin-server/src/competition/test/competition.controller.spec.ts
  apps/admin-server/src/competition/test/competition.service.spec.ts
  apps/admin-server/src/prisma/prisma.service.ts
Labels: feat, needToFixFeat, HOTFIX

#68 feature:: writeProject
  apps/asset-server/src/prisma/prisma.service.ts
  apps/asset-server/src/prisma/schema.prisma
  apps/asset-server/src/road/dto/request/write.request.dto.ts
  apps/asset-server/src/road/road.controller.ts
  apps/asset-server/src/road/road.module.ts
  apps/asset-server/src/road/road.service.ts
  apps/asset-server/src/road/test/road.controller.spec.ts
  apps/asset-server/src/road/test/road.service.spec.ts
  package.json
Labels: feat
